/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Arrow.gltf --transform
Author: aidanp (https://sketchfab.com/bionic_leaf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jumpboost-arrow-fad95c37aaa240e49377edcfe2552ee7
Title: Jump/Boost Arrow
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Arrow-transformed.glb");
  return (
    <group {...props} dispose={null} scale={0.015}>
      <mesh
        geometry={nodes.Cube__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / -2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/Arrow-transformed.glb");
