/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Calcu.gltf --transform
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/calculator-c78f13f842714863800899014754392a
Title: Calculator
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Calcu-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.8} >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01} position={[0, 0, -1]}>
          <mesh
            geometry={nodes.calc001_low_calc_0.geometry}
            material={materials.calc}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            
          />
          <mesh
            geometry={nodes.calc002_low_calc_0.geometry}
            material={materials.calc}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.calc_low_calc_0.geometry}
            material={materials.calc}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.calc003_low_calc_0.geometry}
            material={materials.calc}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.calc004_low_calc_0.geometry}
            material={materials.calc}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Calcu-transformed.glb");
