/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Paper.gltf --transform
Author: NameSsis (https://sketchfab.com/NameSsis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-tablet-f2b7978367164eb38167dd4832978288
Title: Paper Tablet
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Paper-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.7}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Plane_Material_0.geometry}
            material={materials.Material}
            scale={100}
          />
          <mesh
            geometry={nodes.Plane005_Material002_0.geometry}
            material={materials["Material.002"]}
            position={[-0.08, 11.2, 0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Paper-transformed.glb");
