/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Target.gltf --transform
Author: AyoubBani (https://sketchfab.com/AyoubBani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-bar-target-arrow-03e07087107944f8957571f8ce4bcaa4
Title: Game Bar Target Arrow
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Target-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.015}>
        <group
          position={[7.22, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.Cylinder_arrow_red_0.geometry}
            material={materials.arrow_red}
          />
          <mesh
            geometry={nodes.Cylinder_target_white_0.geometry}
            material={materials.target_white}
          />
        </group>
        <group
          position={[101.75, 0.02, -0.04]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
          scale={130.86}
        >
          <mesh
            geometry={nodes.Cylinder001_arrow_red_0.geometry}
            material={materials.arrow_red}
          />
          <mesh
            geometry={nodes.Cylinder001_Gold_0.geometry}
            material={materials.Gold}
          />
          <mesh
            geometry={nodes.Cylinder001_Material002_0.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Target-transformed.glb");
